### ISSUE TITLE
Add best model with Git LFS & GHA Workflow update

### ISSUE THREAD

**Issue by Hedredo** [Hedredo/oc_p8#21]
Track the file with git lfs
```
git lfs track "app/model/best_model.keras"
```
Add, commit and push the .gitattributes.
Adapt the GHA workflow then:

```
name: Build & Push Docker Image after modifying the api

on:
    push:
      paths:
        - 'app/**'  # Exécuter le workflow uniquement si le code du conteneur est modifié

env:
    DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    APP_NAME: app
    DOCKER_IMAGE_PATH: hedredo/segmentation_api:latest
  
jobs:
  build-push:
    runs-on: ubuntu-latest # Same as the container image
  
    steps:
      # Étape 1 : Cloner le dépôt avec LFS
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true  # Cette option permet de télécharger les fichiers gérés par LFS

      # Étape 2 : Installer Git LFS
      - name: Set up Git LFS
        run: |
          git lfs install  # Assure que Git LFS est bien installé et configuré

      # Étape 3 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      # Étape 4 : Installer les dépendances du conteneur à tester
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./${{ env.APP_NAME }}/requirements.txt

      # Étape 5 : Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_PATH }} ./${{ env.APP_NAME }}

      # Étape 6 : Docker login using the Docker login action
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Étape 7 : Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE_PATH }}
```
